# Generated by Django 5.1.9 on 2025-05-20 19:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('cover', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(default='English', max_length=50)),
                ('release_date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('history', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_pic', models.ImageField(default='reader_profiles/default.png', upload_to='reader_profiles/')),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReaderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('is_returned', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('pending', 'Pending')], default='borrowed', max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to='core.reader')),
            ],
            options={
                'ordering': ['-return_date'],
            },
        ),
    ]
