# Generated by Django 5.1.9 on 2025-05-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='password',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
